version: '3.7'
services:
  web:
    container_name: leave-migration-ui
    build:
      context: ./frontend
      args:
        app_env: production
    restart: always
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080
  api:
    container_name: leave-migration-api
    build:
      context: .
    restart: always
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - '.:/app'
